Repository jamulussoftware/jamulus, pull requests merged in 2021-03, with the labels that each got.

#1141 Update pt_BR translation for 3.7.0 (see jamulussoftware#1086)
  src/res/translation/translation_pt_BR.ts
Labels: translation

#1152 Updated Spanish translation
  src/res/translation/translation_es_ES.ts
  src/res/translation/wininstaller/es.nsi
  src/res/translation/wininstaller/installerlng.nsi
Labels: translation

#1155 Improve version update detection.
  ChangeLog
  src/clientdlg.cpp
  src/global.h
  src/serverdlg.cpp
Labels: improvement

#1148 NSIS: Increase height of ASIO driver explanation label
  windows/installer.nsi
Labels: installer

#1194 windows/sound.cpp: Explicitly set driverInfo to 0
  windows/sound.cpp
Labels: bug

#1319 864-Windows-installer-issue-fix
  windows/installer.nsi
Labels: bug

#1151 Delay pan
  ChangeLog
  src/global.h
  src/main.cpp
  src/server.cpp
  src/server.h
  src/serverdlg.cpp
  src/serverdlg.h
  src/serverdlgbase.ui
Labels: feature request

#1222 Client: Add support for input gain control
  src/client.cpp
  src/client.h
  src/clientdlg.cpp
  src/clientsettingsdlg.cpp
  src/clientsettingsdlg.h
  src/clientsettingsdlgbase.ui
  src/settings.cpp
  src/settings.h
Labels: feature request
