Repository jamulussoftware/jamulus, pull requests merged in 2023-04, with the labels that each got.

#3017 Remove remaining directory server mentions
  src/clientsettingsdlg.cpp
  src/clientsettingsdlg.h
  src/connectdlg.cpp
  src/connectdlg.h
  src/connectdlgbase.ui
  src/main.cpp
  src/protocol.cpp
  src/server.cpp
  src/server.h
  src/serverdlg.cpp
  src/serverlist.cpp
  src/serverlist.h
  src/serverrpc.cpp
  src/settings.cpp
  src/settings.h
  src/util.h
Labels: refactoring, needs documentation

#3048 RPC: remove remaining directory server mentions
  docs/JSON-RPC.md
  src/serverrpc.cpp
Labels: refactoring, needs documentation, JSON-RPC

#3008 Display server title correctly in dark mode
  src/clientdlg.cpp
Labels: bug

#2300 Autobuild: Use Qt6 for Windows 64bit
  .github/autobuild/windows.ps1
Labels: needs documentation
