Repository jamulussoftware/jamulus, pull requests merged in 2023-06, with the labels that each got.

#2996 Bugfix/#2723 self label checkboxes
  src/clientsettingsdlg.cpp
  src/clientsettingsdlgbase.ui
  src/serverdlg.cpp
  src/serverdlgbase.ui
  src/translation/translation_de_DE.qm
  src/translation/translation_de_DE.ts
  src/translation/translation_es_ES.qm
  src/translation/translation_es_ES.ts
  src/translation/translation_fr_FR.qm
  src/translation/translation_fr_FR.ts
  src/translation/translation_it_IT.qm
  src/translation/translation_it_IT.ts
  src/translation/translation_ko_KR.qm
  src/translation/translation_ko_KR.ts
  src/translation/translation_nb_NO.qm
  src/translation/translation_nb_NO.ts
  src/translation/translation_nl_NL.qm
  src/translation/translation_nl_NL.ts
  src/translation/translation_pl_PL.qm
  src/translation/translation_pl_PL.ts
  src/translation/translation_pt_BR.qm
  src/translation/translation_pt_BR.ts
  src/translation/translation_pt_PT.qm
  src/translation/translation_pt_PT.ts
  src/translation/translation_sk_SK.qm
  src/translation/translation_sk_SK.ts
  src/translation/translation_sv_SE.qm
  src/translation/translation_sv_SE.ts
  src/translation/translation_zh_CN.qm
  src/translation/translation_zh_CN.ts
Labels: needs documentation

#3076 MacOS: Fix Xcode build
  Jamulus.pro
  mac/Info-xcode.plist
Labels: bug

#2944 Mac: Enable signing with self signed cert
  .github/autobuild/mac.sh
  .github/workflows/autobuild.yml
Labels: tooling

#3013 Autobuild: Create Debian repository on release
  .github/workflows/autobuild.yml
  linux/setup_repo.sh
Labels: needs documentation
