Repository jamulussoftware/jamulus, pull requests merged in 2023-05, with the labels that each got.

#3052 Add pylint to CI and fix all Python
  .editorconfig
  .github/autobuild/get_build_vars.py
  .github/workflows/coding-style-check.yml
  .pylintrc
  CONTRIBUTING.md
  Jamulus.pro
  src/util.h
  tools/generate_json_rpc_docs.py
  tools/get_release_contributors.py
  tools/qt5_to_qt6_country_code_table.py
Labels: refactoring

#3073 Build: Update iOS Runner and SDK
  .github/workflows/autobuild.yml
Labels: tooling

#3058 #3050 Save HTML formatting in Server Welcome Message
  src/serverdlg.cpp
Labels: good first issue
