Repository jamulussoftware/jamulus, pull requests merged in 2024-12, with the labels that each got.

#3431 Add Windows native MIDI support
  Jamulus.pro
  src/sound/asio/sound.cpp
  src/sound/asio/sound.h
  src/sound/midi-win/midi.cpp
  src/sound/midi-win/midi.h
  src/sound/soundbase.cpp
  src/sound/soundbase.h
Labels: needs documentation, Windows

#3416 Display server versions in Connect dialog
  src/clientdlg.cpp
  src/connectdlg.cpp
  src/connectdlg.h
  src/connectdlgbase.ui
Labels: feature request, needs documentation

#3413 Fix crash on closing iOS chat dialog
  src/chatdlg.cpp
  src/chatdlg.h
Labels: bug

#3441 Translations update from Hosted Weblate
  src/translation/translation_es_ES.ts
  src/translation/translation_fr_FR.ts
  src/translation/translation_pl_PL.ts
Labels: translation

#3444 Upgrade Android Build OS
  .github/workflows/autobuild.yml
Labels: android

#3445 Upgrade iOS Build to Qt6
  .github/autobuild/ios.sh
  .github/workflows/autobuild.yml
Labels: iOS

#3451 Build: Fix windows for qt6.8.1
  .github/autobuild/windows.ps1
  .github/workflows/autobuild.yml
  COMPILING.md
  windows/deploy_windows.ps1
Labels: dependencies
